components:
  schemas:
    ChartCoordinateRequest:
      properties:
        measurement_method:
          enum:
          - height
          - weight
          - ofc
          - bmi
          title: Measurement Method
          type: string
        sex:
          enum:
          - male
          - female
          title: Sex
          type: string
      required:
      - sex
      - measurement_method
      title: ChartCoordinateRequest
      type: object
    FictionalChildRequest:
      properties:
        drift:
          default: false
          title: Drift
          type: boolean
        drift_range:
          default: -0.05
          title: Drift Range
          type: number
        end_age:
          default: 20.0
          title: End Age
          type: number
        gestation_days:
          default: 0
          title: Gestation Days
          type: integer
        gestation_weeks:
          default: 40
          title: Gestation Weeks
          type: integer
        measurement_interval_number:
          default: 20
          title: Measurement Interval Number
          type: integer
        measurement_interval_type:
          default: days
          enum:
          - d
          - day
          - days
          - w
          - week
          - weeks
          - m
          - month
          - months
          - y
          - year
          - years
          title: Measurement Interval Type
          type: string
        measurement_method:
          enum:
          - height
          - weight
          - ofc
          - bmi
          title: Measurement Method
          type: string
        noise:
          default: false
          title: Noise
          type: boolean
        noise_range:
          default: 0.005
          title: Noise Range
          type: number
        reference:
          enum:
          - uk-who
          - trisomy-21
          - turners-syndrome
          title: Reference
          type: string
        sex:
          enum:
          - male
          - female
          title: Sex
          type: string
        start_chronological_age:
          default: 0.0
          title: Start Chronological Age
          type: number
        start_sds:
          default: 0
          title: Start Sds
          type: number
      required:
      - measurement_method
      - sex
      - reference
      title: FictionalChildRequest
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    MeasurementRequest:
      properties:
        birth_date:
          format: date
          title: Birth Date
          type: string
        gestation_days:
          default: 0
          title: Gestation Days
          type: integer
        gestation_weeks:
          default: 40
          title: Gestation Weeks
          type: integer
        measurement_method:
          enum:
          - height
          - weight
          - ofc
          - bmi
          title: Measurement Method
          type: string
        observation_date:
          format: date
          title: Observation Date
          type: string
        observation_value:
          title: Observation Value
          type: number
        sex:
          enum:
          - male
          - female
          title: Sex
          type: string
      required:
      - birth_date
      - observation_date
      - observation_value
      - sex
      - measurement_method
      title: MeasurementRequest
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: Returns SDS and centiles for child growth measurements using growth
    references.
  title: RCPCH Growth API
  version: 3.0.3
openapi: 3.0.2
paths:
  /trisomy-21/calculation:
    post:
      description: "Centile calculation.\n---\npost:\n  summary: Trisomy 21 centile\
        \ and SDS calculation.\n  description: |\n    * This endpoint MUST ONLY be\
        \ used for children with Trisomy 21 (Down's Syndrome).\n    * Returns a single\
        \ centile/SDS calculation for the selected `measurement_method`.\n    * Gestational\
        \ age correction will be applied automatically if appropriate according to\
        \ the gestational age at birth data supplied.\n    * Available `measurement_method`s\
        \ are: `height`, `weight`, `bmi`, or `ofc` (OFC = occipitofrontal circumference\
        \ = 'head circumference').\n    * Note that BMI must be precalculated for\
        \ the `bmi` function.\n\n  requestBody:\n    content:\n      application/json:\n\
        \        schema: CalculationRequestParameters\n        example:\n        \
        \    birth_date: \"2020-04-12\"\n            observation_date: \"2020-06-12\"\
        \n            observation_value: 60\n            measurement_method: \"height\"\
        \n            sex: male\n            gestation_weeks: 40\n            gestation_days:\
        \ 4\n\n  responses:\n    200:\n      description: \"Centile calculation (single)\
        \ according to the supplied data was returned\"\n      content:\n        application/json:\n\
        \          schema: CalculationResponseSchema"
      operationId: trisomy_21_calculation_trisomy_21_calculation_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Trisomy 21 Calculation
  /trisomy-21/chart-coordinates:
    post:
      description: "Chart data.\n---\nPOST:\n  summary: UK-WHO Chart coordinates in\
        \ plottable format\n    * Returns coordinates for constructing the lines of\
        \ a traditional growth chart, in JSON format\n    * Requires a sex ('male'\
        \ or 'female' lowercase) and a measurement_method ('height', 'weight' ,'bmi',\
        \ 'ofc')\n\n  requestBody:\n    content:\n      application/json:\n      \
        \  schema: ChartDataRequestParameters\n        example:\n            \"sex\"\
        : \"female\"\n            \"measurement_method\":\"height\"\n\n  responses:\n\
        \    200:\n      description: \"Chart data for plotting a traditional growth\
        \ chart was returned\"\n      content:\n        application/json:\n      \
        \    schema: ChartDataResponseSchema"
      operationId: trisomy_21_chart_coordinates_trisomy_21_chart_coordinates_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChartCoordinateRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Trisomy 21 Chart Coordinates
  /trisomy-21/fictional-child-data:
    post:
      operationId: fictional_child_data_trisomy_21_fictional_child_data_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FictionalChildRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Fictional Child Data
  /turner/calculation:
    post:
      description: "Centile calculation.\n---\nPOST:\n  summary: Turner's Syndrome\
        \ centile and SDS calculation.\n  description: |\n    * This endpoint MUST\
        \ ONLY be used for children with the chromosomal disorder Turner's Syndrome\
        \ (45,XO karyotype).\n    * Returns a single centile/SDS calculation for the\
        \ selected `measurement_method`.\n    * Gestational age correction will be\
        \ applied automatically if appropriate according to the gestational age at\
        \ birth data supplied.\n    * Available `measurement_method`s are: `height`,\
        \ `weight`, `bmi`, or `ofc` (OFC = occipitofrontal circumference = 'head circumference').\n\
        \    * Note that BMI must be precalculated for the `bmi` function.\n\n  requestBody:\n\
        \    content:\n      application/json:\n        schema: CalculationRequestParameters\n\
        \        example:\n            birth_date: \"2020-04-12\"\n            observation_date:\
        \ \"2020-06-12\"\n            observation_value: 60\n            measurement_method:\
        \ \"height\"\n            sex: male\n            gestation_weeks: 40\n   \
        \         gestation_days: 4\n\n  responses:\n    200:\n      description:\
        \ \"Centile calculation (single) according to the supplied data was returned\"\
        \n      content:\n        application/json:\n          schema: CalculationResponseSchema"
      operationId: turner_calculation_turner_calculation_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Turner Calculation
  /turner/chart-coordinates:
    post:
      description: "Chart data.\n---\nPOST:\n  summary: UK-WHO Chart coordinates in\
        \ plottable format\n    * Returns coordinates for constructing the lines of\
        \ a traditional growth chart, in JSON format\n    * Note height in girls conly\
        \ be only returned. It is a post request to maintain consistency with other\
        \ routes.\n\n  requestBody:\n    content:\n      application/json:\n     \
        \   schema: ChartDataRequestParameters\n\n  responses:\n    200:\n      description:\
        \ \"Chart data for plotting a traditional growth chart was returned\"\n  \
        \    content:\n        application/json:\n          schema: ChartDataResponseSchema"
      operationId: turner_chart_coordinates_turner_chart_coordinates_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChartCoordinateRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Turner Chart Coordinates
  /turner/fictional-child-data:
    post:
      operationId: fictional_child_data_turner_fictional_child_data_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FictionalChildRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Fictional Child Data
  /uk-who/calculation:
    post:
      description: "Centile calculation.\n---\nPOST:\n  summary: UK-WHO centile and\
        \ SDS calculation.\n  description: |\n    * These are the 'standard' centiles\
        \ for children in the UK. It uses a hybrid of the WHO and UK90 datasets.\n\
        \    * For non-UK use you may need the WHO-only or CDC charts which we do\
        \ not yet support, but we may add if demand is there.\n    * Returns a single\
        \ centile/SDS calculation for the selected `measurement_method`.\n    * Gestational\
        \ age correction will be applied automatically if appropriate according to\
        \ the gestational age at birth data supplied.\n    * Available `measurement_method`s\
        \ are: `height`, `weight`, `bmi`, or `ofc` (OFC = occipitofrontal circumference\
        \ = 'head circumference').\n    * Note that BMI must be precalculated for\
        \ the `bmi` function.\n\n  requestBody:\n    content:\n      application/json:\n\
        \        schema: CalculationRequestParameters\n        example:\n        \
        \    birth_date: \"2020-04-12\"\n            observation_date: \"2020-06-12\"\
        \n            observation_value: 60\n            measurement_method: \"height\"\
        \n            sex: male\n            gestation_weeks: 40\n            gestation_days:\
        \ 4\n\n  responses:\n    200:\n      description: \"Centile calculation (single)\
        \ according to the supplied data was returned\"\n      content:\n        application/json:\n\
        \          schema: CalculationResponseSchema"
      operationId: uk_who_calculation_uk_who_calculation_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Uk Who Calculation
  /uk-who/chart-coordinates:
    post:
      description: "Chart data.\n---\nPOST:\n  summary: UK-WHO Chart coordinates in\
        \ plottable format\n    * Returns coordinates for constructing the lines of\
        \ a traditional growth chart, in JSON format\n\n  requestBody:\n    content:\n\
        \      application/json:\n        schema: ChartDataRequestParameters\n\n \
        \ responses:\n    200:\n      description: \"Chart data for plotting a traditional\
        \ growth chart was returned\"\n      content:\n        application/json:\n\
        \          schema: ChartDataResponseSchema"
      operationId: uk_who_chart_coordinates_uk_who_chart_coordinates_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChartCoordinateRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Uk Who Chart Coordinates
  /uk-who/fictional-child-data:
    post:
      operationId: fictional_child_data_uk_who_fictional_child_data_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FictionalChildRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Fictional Child Data
